version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.126.13.37 << 'EOF'
              cd /var/www/html/your-app
              git pull origin main
              npm ci
              npm start
            EOF
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
