version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Zin5ieaRTsz2lv2q3+/viGu9Gj5kBPbCK9H2fRvhzFI asamprabhakarbala@gmail.com"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.126.13.37 \<< 'EOF'
              cd /var/www/html/your-app
              git pull origin main
              npm install
              pm2 restart all
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
